# Generated by Django 2.2.5 on 2020-12-28 14:12

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201228_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, upload_to='', verbose_name=rooms.models.Photo),
        ),
    ]
