# Generated by Django 2.2.5 on 2021-01-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rulse',
            new_name='house_rules',
        ),
    ]
